export const globalConstants = {
  MYSQL: 'mysql',
  LOCALHOST: 'localhost',
  PORT: 3306,
  ROOT_USER: 'root',
  ROOT_PASS: 'root',
  TEST: 'test',
  USER_EXIST: 'User already exists',
  BAD_REQUEST: 'Bad request',
  DB_URL: 'mongodb://localhost/demo',
  TOKEN_EXP_TIME: '86400s',
  AUTH_GUARD_LOCAL_TYPE: 'local',
  AUTH_GUARD_JWT_TYPE: 'jwt',
  EMAIL: 'email',
  PASSWORD: 'password',
  USERS: 'users',
  SEND_EMAIL: "email",
  ID: 'id',
  PUT: 'PUST',
  POST: 'POST',
  DELETE: 'DELETE',
  LOGIN: 'auth/login',
  LOGOUT: 'auth/logout',
  SIGN_UP: 'auth/signup',
  SPACE: ' ',
  TOKEN_USERNAME: 'username',
  SECRET: 'mustafa',
  SENDER_EMAIL: 'furqanbutt6900@gmail.com',
  TEST_EMAIL: 'test@gmail.com',
  TEST_PASSWORD: '$2b$10$NFr5O/Y4aQiJPTDuxzqh6et7fPMQjs2fJyQISxGP8KYK3A1uAIlqy',
  TEST_GENDER: 'male'
};
